spring:
  profiles:
    active: ${APP_PROFILE:jpa}
  main:
    banner-mode: "off"
server:
  port: 8080
carrent:
  json:
    users-file: ${CARENT_USERS_FILE:users.json}
    vehicles-file: ${CARENT_VEHICLES_FILE:vehicles.json}
    rentals-file: ${CARENT_RENTALS_FILE:rentals.json}
    categories-file: ${CARENT_CATEGORIES_FILE:categories.json}
